spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: delivery
    password: 0987
  redis:
    host: localhost
    password: 0987
    session.port: 6379
    cache.port: 6389
    cart.port: 6399
    delivery.port: 6409

mybatis:
  # mapper가 위치한 경로 설정
  mapper-locations: mapper/**/*.xml
